#!/usr/bin/env bash

source /vconf/Test.conf

iperf3 --version | tail -1

echo "server: ${IPERF_SERVER}"
NIC=$(/vbin/get-nic)
IP=$(/vbin/get-ip)
echo "client: ${IP}"

echo "kernel release: $(uname --kernel-release)"
echo "kernel version: $(uname --kernel-version)"
DRIVER=$(sudo ethtool -i wlan0 | grep "^driver" | awk '{print $2}')
echo "driver: ${DRIVER}"
echo "driver version: $(sudo ethtool -i wlan0 | grep "^version" | awk '{print $2}')"
echo "module filename: $(sudo modinfo brcmfmac | grep "^filename" | awk '{print $2}')"
