#!/usr/bin/env bash

set -eo pipefail

source /vconf/Test.conf

iperf3 --version | tail -1

echo "server: ${IPERF_SERVER}"
NIC=$(/vbin/get-nic)
IP=$(/vbin/get-ip)
echo "client: ${IP}"

START=$(date)

TIMESTAMP=$(date +%s)
DOWNLOAD_INTERVALS="/tmp/download-intervals-${TIMESTAMP}.log"
UPLOAD_INTERVALS="/tmp/upload-intervals-${TIMESTAMP}.log"

COUNTER=0
while [ "${COUNTER}" -lt "${MAX_TESTS}" ]
do
	DOWNLOAD_SUMMARY=$(IP=$IP IPERF_SERVER=$IPERF_SERVER INTERVAL_LOG=$DOWNLOAD_INTERVALS /vbin/download)
	echo "${DOWNLOAD_SUMMARY}"

	sleep 5

	UPLOAD_SUMMARY=$(IP=$IP IPERF_SERVER=$IPERF_SERVER INTERVAL_LOG=$UPLOAD_INTERVALS TIMESTAMP=$TIMESTAMP /vbin/upload)
	echo "${UPLOAD_SUMMARY}"
	
	let COUNTER=COUNTER+1
	
	sleep 5
done

echo "================================================"

iperf3 --version | tail -1

echo "server: ${IPERF_SERVER}"
NIC=$(/vbin/get-nic)
IP=$(/vbin/get-ip)
echo "client: ${IP}"

echo "kernel release: $(uname --kernel-release)"
echo "kernel version: $(uname --kernel-version)"
DRIVER=$(sudo ethtool -i wlan0 | grep "^driver" | awk '{print $2}')
echo "driver: ${DRIVER}"
echo "driver version: $(sudo ethtool -i wlan0 | grep "^version" | awk '{print $2}')"
echo "module filename: $(sudo modinfo brcmfmac | grep "^filename" | awk '{print $2}')"

echo "started: ${START}"
echo "ended: $(date)"

echo "download stats:"
/vbin/analyze "${DOWNLOAD_INTERVALS}"

echo "upload stats:"
/vbin/analyze "${UPLOAD_INTERVALS}"
